[package]
name = "wordspunch"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
ratatui = "0.28.0"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
